[package]
name = "digital_asset_launchpad"
version = "1.0.0"
authors = []

# [addresses]
# launchpad_addr = "_"
# initial_creator_addr = "_"
# minter = "_"
# platform_creator_addr = "_" 
# marketplace_addr = "_"

[dev-addresses]
launchpad_addr = "0x1234"
initial_creator_addr = "0x5678"
minter = "0x9abc"
platform_creator_addr = "0xdef0" 
marketplace_addr = "0x4321"

[addresses]
launchpad_addr = "_"
initial_creator_addr = "_"
minter = "_"
marketplace_addr = "_"
platform_creator_addr = "_"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "main", subdir = "token-minter" }


[dev-dependencies]