[package]
name = "digital_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = "_"
initial_creator_addr = "0x9bdcec04cd0aa9f0fcf3bef12a09a62011cd66ba27cf778a2e4479fa92589a8"
minter = "0x3c41ff6b5845e0094e19888cba63773591be9de59cafa9e582386f6af15dd490"
platform_creator_addr = "0x9bdcec04cd0aa9f0fcf3bef12a09a62011cd66ba27cf778a2e4479fa92589a8" 
marketplace_addr = "0x9bdcec04cd0aa9f0fcf3bef12a09a62011cd66ba27cf778a2e4479fa92589a8"

[dev-addresses]
launchpad_addr = "0x1234"
initial_creator_addr = "0x5678"
minter = "0x9abc"
platform_creator_addr = "0xdef0" 
marketplace_addr = "0x4321"

# [addresses]
# launchpad_addr = "0x1234"
# initial_creator_addr = "0x5678"
# minter = "0x9abc"
# marketplace_addr = "0x4321"
# platform_creator_addr = "0xdef0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "main", subdir = "token-minter" }


[dev-dependencies]